### ISSUE TITLE
repay from salary

### ISSUE THREAD

**Issue by adhennon** [frappe/lending#146]
### Information about bug

repay from salary checkbox was removed from loan doctype in erp next version 14 but we still get issues when submitting loan doctype like this one

AttributeError: 'Loan' object has no attribute 'repay_from_salary'

### Module

Loan Management

### Version

ERPNext: v14.46.1 (version-14)

Frappe Framework: v14.54.0 (version-14)

### Installation method

docker

### Relevant log output / Stack trace / Full Error Message.

```shell
### App Versions

{
	"erpnext": "14.46.1",
	"frappe": "14.54.0",
	"hrms": "16.0.0-dev"
}
```
### Route
```
Form/Loan/new-loan-myogzjlkmu
```
### Traceback
```
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 95, in application
    response = frappe.api.handle()
  File "apps/frappe/frappe/api.py", line 54, in handle
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 47, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 85, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1622, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/desk/form/save.py", line 31, in savedocs
    doc.save()
  File "apps/frappe/frappe/model/document.py", line 309, in save
    return self._save(*args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 331, in _save
    return self.insert()
  File "apps/frappe/frappe/model/document.py", line 262, in insert
    self.run_before_save_methods()
  File "apps/frappe/frappe/model/document.py", line 1055, in run_before_save_methods
    self.run_method("validate")
  File "apps/frappe/frappe/model/document.py", line 919, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1281, in composer
    return composed(self, method, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1265, in runner
    add_to_return_value(self, f(self, method, *args, **kwargs))
  File "apps/hrms/hrms/hr/utils.py", line 687, in validate_loan_repay_from_salary
    if doc.applicant_type == "Employee" and doc.repay_from_salary:
AttributeError: 'Loan' object has no attribute 'repay_from_salary'
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kittiu** [comment]
I got the same error on Version 15

![image](https://github.com/frappe/lending/assets/1973598/45ac9e3f-83b0-441b-8b08-443f399cb569)

Currently, I have to add back this field to remove the error from my productoin.

**Comment by mohsinalimat** [comment]
Facing same issue

**Comment by deepeshgarg007** [comment]
This should get added when you install the HRMS application. If the issue still persists, please raise an issue on the HRMS repo
