### ISSUE TITLE
Error adding loan repayment missing column in Loan product.

### ISSUE THREAD

**Issue by abhinavxd** [frappe/lending#147]
### Information about bug

The `charges_receivable_account` field is missing in `Loan Product` doctype.
The same field is being used in loan_repayment.py

Added stacktrace for reference.

### Module

Loan Management

### Version

"erpnext": "15.0.0-dev",
"frappe": "15.0.0-dev",
"india_compliance": "16.0.0-dev",
"lending": "0.0.1",

### Installation method

None

### Relevant log output / Stack trace / Full Error Message.

```shell
### App Versions

{
	"erpnext": "15.0.0-dev",
	"frappe": "15.0.0-dev",
	"india_compliance": "16.0.0-dev",
	"lending": "0.0.1",
}
```
### Route
```
Form/Loan Repayment/LM-REP-56902
```
### Traceback
```
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 110, in application
    response = frappe.api.handle(request)
  File "apps/frappe/frappe/api/__init__.py", line 49, in handle
    data = endpoint(**arguments)
  File "apps/frappe/frappe/api/v1.py", line 36, in handle_rpc_call
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 49, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 85, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1677, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "apps/frappe/frappe/desk/form/save.py", line 37, in savedocs
    doc.submit()
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1038, in submit
    return self._submit()
  File "apps/frappe/frappe/model/document.py", line 1019, in _submit
    return self.save()
  File "apps/frappe/frappe/model/document.py", line 334, in save
    return self._save(*args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 386, in _save
    self.run_post_save_methods()
  File "apps/frappe/frappe/model/document.py", line 1121, in run_post_save_methods
    self.run_method("on_submit")
  File "apps/frappe/frappe/model/document.py", line 950, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1316, in composer
    return composed(self, method, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1298, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "apps/frappe/frappe/model/document.py", line 947, in fn
    return method_object(*args, **kwargs)
  File "apps/lending/lending/loan_management/doctype/loan_repayment/loan_repayment.py", line 56, in on_submit
    self.make_gl_entries()
  File "apps/lending/lending/loan_management/doctype/loan_repayment/loan_repayment.py", line 634, in make_gl_entries
    account_details = frappe.db.get_value(
  File "apps/frappe/frappe/database/database.py", line 466, in get_value
    result = self.get_values(
  File "apps/frappe/frappe/database/database.py", line 563, in get_values
    out = self._get_values_from_table(
  File "apps/frappe/frappe/database/database.py", line 827, in _get_values_from_table
    return query.run(as_dict=as_dict, debug=debug, update=update, run=run, pluck=pluck)
  File "apps/frappe/frappe/query_builder/utils.py", line 87, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
  File "apps/frappe/frappe/database/database.py", line 217, in sql
    self._cursor.execute(query, values)
  File "env/lib/python3.10/site-packages/pymysql/cursors.py", line 153, in execute
    result = self._query(query)
  File "env/lib/python3.10/site-packages/pymysql/cursors.py", line 322, in _query
    conn.query(q)
  File "env/lib/python3.10/site-packages/pymysql/connections.py", line 558, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "env/lib/python3.10/site-packages/pymysql/connections.py", line 822, in _read_query_result
    result.read()
  File "env/lib/python3.10/site-packages/pymysql/connections.py", line 1200, in read
    first_packet = self.connection._read_packet()
  File "env/lib/python3.10/site-packages/pymysql/connections.py", line 772, in _read_packet
    packet.raise_for_error()
  File "env/lib/python3.10/site-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "env/lib/python3.10/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1054, "Unknown column 'charges_receivable_account' in 'field list'")

```
### Request Data
```
{
	"type": "POST",
	"args": {
      REDACTED
	},
	"btn": {
		"jQuery370048498111882097251": {
			"events": {
				"click": [
					{
						"type": "click",
						"origType": "click",
						"guid": 1696,
						"namespace": ""
					}
				]
			}
		}
	},
	"freeze": true,
	"headers": {},
	"error_handlers": {},
	"url": "/api/method/frappe.desk.form.save.savedocs",
	"request_id": null
}
```
### Response Data
```
{
	"exception": "pymysql.err.OperationalError: (1054, \"Unknown column 'charges_receivable_account' in 'field list'\")",
	"exc_type": "OperationalError",
	"_exc_source": "lending (app)"
}
```
```


### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by federicocalvo** [comment]
Hi, i have the same issue

**Comment by mubi64** [comment]
@deepeshgarg007 can you please let me know how to fix this issue?
