### ISSUE TITLE
Error while installing the app

### ISSUE THREAD

**Issue by akhashogji** [frappe/lending#157]
### Information about bug

I got the error `An error occurred while installing lending: Cannot link cancelled document: Loan: ACC-LOAN-2023-00006` while installing the app, which led to a lot problems post-that. I had to manually delete the cancelled docs (total: 3) from the Db for it to go through. Can we have a proper way to handle it? 

Waiting on a solution before upgrading my production enviornment

### Module

Loan Management

### Version

ERPNext: v15.8.3 (version-15)
Frappe Framework: v15.7.0 (version-15)
Frappe HR: v15.7.1 (version-15)
Ksa: v0.0.1 (dev)
Frappe Lending: v0.0.1 (version-15)
Payments: v0.0.1 (develop)

### Installation method

manual install

### Relevant log output / Stack trace / Full Error Message.

```shell
ubuntu@ec2-54-84-187-196:~/frappe-bench$ bench --site $sitename install-app lending
App erpnext already installed

Installing lending...

Updating DocTypes for lending       : [========================================] 100%

Running post-install patches to patch existing data...

An error occurred while installing lending: Cannot link cancelled document: Loan: ACC-LOAN-2023-00006
Traceback (most recent call last):
  File "apps/frappe/frappe/commands/site.py", line 462, in install_app
    _install_app(app, verbose=context.verbose, force=force)
  File "apps/frappe/frappe/installer.py", line 311, in install_app
    frappe.get_attr(after_install)()
  File "apps/lending/lending/install.py", line 236, in after_install
    run_patches(get_post_install_patches())
  File "apps/lending/lending/install.py", line 227, in run_patches
    frappe.get_attr(f"lending.patches.v15_0.{patch}.execute")()
  File "apps/lending/lending/patches/v15_0/generate_loan_repayment_schedule.py", line 39, in execute
    loan_repayment_schedule.submit()
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1038, in submit
    return self._submit()
  File "apps/frappe/frappe/model/document.py", line 1019, in _submit
    return self.save()
  File "apps/frappe/frappe/model/document.py", line 334, in save
    return self._save(*args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 356, in _save
    return self.insert()
  File "apps/frappe/frappe/model/document.py", line 278, in insert
    self._validate_links()
  File "apps/frappe/frappe/model/document.py", line 922, in _validate_links
    frappe.throw(_("Cannot link cancelled document: {0}").format(msg), frappe.CancelledLinkError)
  File "apps/frappe/frappe/__init__.py", line 603, in throw
    msgprint(
  File "apps/frappe/frappe/__init__.py", line 575, in msgprint
    _raise_exception()
  File "apps/frappe/frappe/__init__.py", line 526, in _raise_exception
    raise exc
frappe.exceptions.CancelledLinkError: Cannot link cancelled document: Loan: ACC-LOAN-2023-00006
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by deepeshgarg007** [comment]
Should be fixed via https://github.com/frappe/lending/pull/158
