### ISSUE TITLE
Error on installing Lending 

### ISSUE THREAD

**Issue by Sendipad** [frappe/lending#8]
### Information about bug

An error occurred while installing lending: HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/frappe/erpnext (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f26b7c13250>: Failed to establish a new connection: [Errno -2] Name or service not known'))

### Module

Loan Management

### Version

Frappe version 14.48.1
Erpnext version v14.38.0

### Installation method

manual install

### Relevant log output / Stack trace / Full Error Message.

```shell
An error occurred while installing lending: HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/frappe/erpnext (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f26b7c13250>: Failed to establish a new connection: [Errno -2] Name or service not known'))
Traceback (most recent call last):
  File "apps/frappe/frappe/installer.py", line 218, in fetch_details_from_tag
    org, repo = org_repo
ValueError: not enough values to unpack (expected 2, got 1)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "env/lib/python3.10/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "env/lib/python3.10/site-packages/urllib3/util/connection.py", line 72, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/lib/python3.10/socket.py", line 955, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "env/lib/python3.10/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "env/lib/python3.10/site-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "env/lib/python3.10/site-packages/urllib3/connectionpool.py", line 1042, in _validate_conn
    conn.connect()
  File "env/lib/python3.10/site-packages/urllib3/connection.py", line 363, in connect
    self.sock = conn = self._new_conn()
  File "env/lib/python3.10/site-packages/urllib3/connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7f26b7c13250>: Failed to establish a new connection: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "env/lib/python3.10/site-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
  File "env/lib/python3.10/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "env/lib/python3.10/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/frappe/erpnext (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f26b7c13250>: Failed to establish a new connection: [Errno -2] Name or service not known'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "apps/frappe/frappe/commands/site.py", line 415, in install_app
    _install_app(app, verbose=context.verbose, force=force)
  File "apps/frappe/frappe/installer.py", line 268, in install_app
    required_app = parse_app_name(app)
  File "apps/frappe/frappe/installer.py", line 248, in parse_app_name
    _, repo, _ = fetch_details_from_tag(name)
  File "apps/frappe/frappe/installer.py", line 220, in fetch_details_from_tag
    org, repo = find_org(org_repo[0])
  File "apps/frappe/frappe/installer.py", line 188, in find_org
    response = requests.head(f"https://api.github.com/repos/{org}/{org_repo}")
  File "env/lib/python3.10/site-packages/requests/api.py", line 100, in head
    return request("head", url, **kwargs)
  File "env/lib/python3.10/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "env/lib/python3.10/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "env/lib/python3.10/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "env/lib/python3.10/site-packages/requests/adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/frappe/erpnext (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f26b7c13250>: Failed to establish a new connection: [Errno -2] Name or service not known'))
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by anandbaburajan** [comment]
@Sendipad seems like you're trying to install lending on erpnext v14.38.0. Loan Management module is already available on erpnext v14, so no need to install lending. Lending is only required from erpnext v15 onwards. I guess we need to mention that somewhere on the readme -- would that have been helpful?

**Comment by deepeshgarg007** [comment]
Doesn't seem like an app-specific issue
